name: Metrics
on:
  # Roda todos os dias à meia-noite
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente clicando num botão
  workflow_dispatch:
  # Roda a cada push na branch master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token padrão do GitHub (já vem configurado)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Opções visuais
          user: AnaLuiza3250
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Plugin de Linguagens (O que você queria!)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_details: bytes-size, percentage
